### ISSUE TITLE
How to set up NAT gateway for private Cloud Networks

### ISSUE THREAD

**Issue by ravi-ojha** [hetzneronline/community-content#1105]
## Problem

The setup recommends DHCP approach however the private instance loses connection in less than 24 hours. You can reproduce the issue. I verified it happens with two private instances and continued to just restart for 3 days to get it back up. 

## Suggested Fix

I haven't fixed it yet. Still looking for a resolution. AI and internet suggests that it should not use DHCP, instead it should be using static config.

**Comment by ravi-ojha** [comment]
I'm sorry I haven't suggested any fix. I'll report back in a couple of days.

**Comment by priyashpatil** [comment]
Facing the same issue, connection is lost after 24hrs

**Comment by priyashpatil** [comment]
Found a fix that worked so far 24hrs plus. Heads Up! **THIS IS AI GENERATED SOLUTION**.

Nat Server
```
#cloud-config
package_update: true
package_upgrade: true
packages:
  - ufw 

write_files:
  - path: /etc/ufw/sysctl.conf
    permissions: '0644'
    content: |
      net/ipv4/ip_forward=1
      # If you plan to use IPv6 NAT (more complex setup):
      # net/ipv6/conf/default/forwarding=1
      # net/ipv6/conf/all/forwarding=1

  - path: /etc/default/ufw
    permissions: '0644'
    content: |
      IPV6=yes
      DEFAULT_INPUT_POLICY="DROP"
      DEFAULT_OUTPUT_POLICY="ACCEPT"
      # Allow forwarding by default. Specific forwarding rules will be in before.rules
      DEFAULT_FORWARD_POLICY="ACCEPT"
      DEFAULT_APPLICATION_POLICY="SKIP"
      MANAGE_BUILTINS=no
      IPT_SYSCTL=/etc/ufw/sysctl.conf # UFW will manage sysctl settings

  - path: /etc/ufw/before.rules # This will overwrite the default before.rules
    permissions: '0640'
    content: |
      #
      # rules.before
      #
      # Rules that should be run before the ufw command line added rules.
      #
      # START UFW NAT configuration
      *nat
      :PREROUTING ACCEPT [0:0]
      :INPUT ACCEPT [0:0]
      :OUTPUT ACCEPT [0:0]
      :POSTROUTING ACCEPT [0:0]
      # Forward traffic from 10.0.0.0/16 on enp7s0
      # to eth0
      # Example: -A POSTROUTING -s 10.0.0.0/16 -o eth0 -j MASQUERADE
      -A POSTROUTING -s 10.0.0.0/16 -o eth0 -j MASQUERADE
      COMMIT
      # END UFW NAT configuration
      
      # START UFW Filter table additions for forwarding
      *filter
      :ufw-before-input - [0:0]
      :ufw-before-output - [0:0]
      :ufw-before-forward - [0:0]
      :ufw-not-local - [0:0]
      
      # Allow all on loopback - standard rule, helps with ping to self & local services
      -A ufw-before-input -i lo -j ACCEPT
      -A ufw-before-output -o lo -j ACCEPT
      
      # Allow forwarding of established and related connections
      -A ufw-before-forward -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
      
      # Allow forwarding from private network to public internet
      # Example: -A ufw-before-forward -i enp7s0 -o eth0 -s 10.0.0.0/16 -j ACCEPT
      -A ufw-before-forward -i enp7s0 -o eth0 -s 10.0.0.0/16 -j ACCEPT
      
      # Standard before.rules content (simplified)
      # Drop invalid packets
      -A ufw-before-input -m conntrack --ctstate INVALID -j DROP
      
      # Connection tracking for input and output
      -A ufw-before-input -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
      
      # Allow ICMP echo requests (ping) to the host itself - enables ping to self
      -A ufw-before-input -p icmp --icmp-type echo-request -j ACCEPT
      
      -A ufw-before-output -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
      
      # ufw-not-local chain (basic definition)
      -A ufw-not-local -m addrtype --dst-type LOCAL -j RETURN
      -A ufw-not-local -m addrtype --dst-type MULTICAST -j RETURN
      -A ufw-not-local -m addrtype --dst-type BROADCAST -j RETURN
      -A ufw-not-local -j DROP
      
      COMMIT
      # END UFW Filter table additions

runcmd:
  # Apply sysctl changes from /etc/ufw/sysctl.conf (UFW enable also does this)
  - sysctl -p /etc/ufw/sysctl.conf

  # Configure UFW basic rules
  - ufw --force disable # Disable first to apply changes cleanly
  - ufw allow OpenSSH # Allow SSH access to the gateway (from public internet)
  - ufw allow in on enp7s0 from 10.0.0.0/16
  - ufw --force enable
```

Private Server
```
#cloud-config
package_update: false
package_upgrade: false

write_files:
  - path: /etc/netplan/99-nat-gateway-route.yaml
    permissions: '0644'
    content: |
      network:
        version: 2
        ethernets:
          enp7s0:
            # hc-utils (Hetzner utility) typically configures this interface for DHCP.
            # This netplan config will be merged and add/override specific settings.
            dhcp4: true # Rely on DHCP for IP address and subnet mask from Hetzner private network
            # dhcp4-overrides:
            #   use-routes: false # Optional: If you want to ensure no default routes from DHCP on this interface.
                                  # Hetzner's private DHCP usually doesn't push a 0.0.0.0/0 route.
            nameservers:
              addresses: [1.1.1.1, 1.0.0.1]
            routes:
              - to: 0.0.0.0/0
                via: 10.0.0.1
                # metric: 100 # Optional: set a metric if you have other routes

runcmd:
  - netplan apply
```

**Comment by priyashpatil** [comment]
The above is not the right solution there some routing issues in single subnet. Also the solution seems very complicated. I tried reaching out support but they refused to help citing it's a community article and support is only paid.

But after a bit more debugging, I think issue with the article is maybe some typos. The setup might as simple as

Hetzner Gateway - Add private server discovery and hetzner cloud route forwards traffic to Nat Gateway
NAT Gateway would only ip forward and MASQUERADE
Private Servers would only need default route that point to Hetzner Gateway.

I think article initially explains this but later OS specific configurations are I think typos.

I still need to verify if this setup work for more than 24 hrs.

**Comment by andrejcremoznik** [comment]
Hi @priyashpatil , did you confirm your solution?

**Comment by priyashpatil** [comment]
Yes it's works. The solution is in the start of the article, later explanation is faulty.  Though I decided not to use NAT setup due to high availability concerns.

But the setup should be like

For hetzner network 10.0.0.1/16; IP Address 10.0.0.1 becomes hetzners default gateway as it's the first IP in the network.

Now in the same network assuming you'll be putting the NAT gateway server on 10.0.0.2 IP you'll create a route cloud route in hetzner that would forward 0.0.0.0/0 traffic to 10.0.0.2

Then in your NAT gateway 10.0.0.2 and with public IPv4 you add the masquerade and ipv4 forwarding 

And finally in private servers you add route to  0.0.0.0/0 to 10.0.0.1

So it works like your private server 10.0.0.3+ would forward traffic to hetzner 10.0.0.1 and then considering cloud rule hetzner gateway would forward the traffic to 10.0.0.2 and masquerade would forward to Internet.

It has to be done like this because these are virtual servers and are not connected at hardware level. So hetzner gateway 10.0.0.1 takes that first ip to facilitate in network communication otherwise server communication won't work. Hetzner installs the the dhcp utility which handles default connectivity but in case of NAT gateway we have to add the rules and setup masquerade

**Comment by andrejcremoznik** [comment]
Well, here's my solution as a cloud init script for Ubuntu cloud image because I'm too lazy to explain everything.

Given these settings:

* private subnet `10.0.0.0/24`
* gateway `10.0.0.1`

**The NAT server** - will use the first available IP so  `10.0.0.2`. This needs to be created first.

```yml
#cloud-config
users: []

runcmd:
  # purge conflicting things
  - systemctl disable --now ufw.service
  - apt-get purge -y ufw hc-utils
  # admin user
  # NOTE: Set the password and admin keys below
  #  - generate password: `openssl rand -base64 24`
  - useradd -m -G sudo -s /usr/bin/bash -p $(openssl passwd -6 "RANDOM_PASSWORD_HERE") admin
  - mkdir -p /home/admin/.ssh
  - echo "ssh-ed25519 ...your...key" >> /home/admin/.ssh/authorized_keys
  - chown -R admin:admin /home/admin
  # packages
  - apt-get update -y
  - apt-get dist-upgrade -y
  - apt-get install -y ca-certificates curl debian-keyring debian-archive-keyring apt-transport-https firewalld
  # install and configure firewalld - this will configure NAT routing for private subnet
  - systemctl enable --now firewalld.service
  - firewall-cmd --permanent --zone=trusted --add-port=52022/tcp
  # NOTE: set trusted sources correctly (private subnet, your home IP) - these will be able to connect to ports in trusted zone
  - firewall-cmd --permanent --zone=trusted --add-source=10.0.0.0/24
  - firewall-cmd --permanent --zone=trusted --add-source=X.X.X.X/24
  - firewall-cmd --permanent --zone=public --add-masquerade
  - firewall-cmd --permanent --zone=public --add-interface=eth0
  - firewall-cmd --reload
  # use netplan to configure private net - uses the config created below
  - netplan generate
  - netplan apply
  - reboot

write_files:
  - path: /etc/ssh/sshd_config.d/sshd.conf
    content: |
      Port 52022
      PermitRootLogin no
      PubkeyAuthentication yes
      AuthorizedKeysFile .ssh/authorized_keys
      PasswordAuthentication no
  - path: /etc/sysctl.d/ip_forward.conf
    content: |
      net.ipv4.ip_forward = 1
      net.ipv6.conf.all.forwarding = 1
  - path: /etc/netplan/60-dhcp.yaml
    permissions: '0400'
    content: |
      network:
        version: 2
        renderer: networkd
        ethernets:
          enp7s0:
            dhcp4: true
```
The `enp7s0` applies to __CX^2, CAX, CPX, CCX^2, CCX^3__ servers, __CX^1, CCX^1__ have `ens10` as the first device according to https://docs.hetzner.com/cloud/networks/server-configuration#almacentosrocky-8-or-higher-fedora

**Private servers**

```yml
#cloud-config
users: []

runcmd:
  # purge conflicting apps
  - systemctl disable --now ufw.service
  - apt-get purge -y ufw hc-utils
  # admin user
  # NOTE: Set the password and admin keys below
  #  - generate password: `openssl rand -base64 24`
  - useradd -m -G sudo -s /usr/bin/bash -p $(openssl passwd -6 "RANDOM_PASSWORD_HERE") admin
  - mkdir -p /home/admin/.ssh
  - echo "ssh-ed25519 ...your...key" >> /home/admin/.ssh/authorized_keys
  - chown -R admin:admin /home/admin
  # ensure network is up (config files put in place by write_files)
  - systemctl restart systemd-networkd.service
  - systemctl restart systemd-resolved.service
  # packages
  - apt-get update -y
  - apt-get dist-upgrade -y
  - reboot

write_files:
  - path: /etc/ssh/sshd_config.d/sshd.conf
    content: |
      Port 22
      PermitRootLogin no
      PubkeyAuthentication yes
      AuthorizedKeysFile .ssh/authorized_keys
      PasswordAuthentication no
  - path: /etc/sudoers.d/custom
    permissions: '0440'
    content: |
      Defaults insults
      Defaults timestamp_timeout=20
      Defaults env_keep += "TERM TERMINFO"
  - path: /etc/systemd/resolved.conf.d/dns.conf
    content: |
      [Resolve]
      DNS=185.12.64.2 185.12.64.1
      FallbackDNS=1.1.1.1
  - path: /etc/systemd/network/dhcp.network
    content: |
      [Match]
      Name=en*
      [Network]
      DHCP=yes
      [Route]
      Gateway=10.0.0.1
      GatewayOnLink=yes
```

Things to note:

* `write_files` runs first, `runcmd` last
* `hc-utils` conflicts with our custom routes and is the source of all problems
* `firewalld` is used on NAT to deal with routing because why the hell not. You need a firewall anyway. I remove `ufw` because it doesn't play nice with docker.

SSH config

```
  Host foobar-ingress
    HostName ingress.domain.tld
    Port 52022

  Host foobar-private1
    ProxyJump project-ingress-env
    HostName 10.0.0.3

  Host foobar-*
    User admin
    IdentityFile ~/.ssh/your_key
```
Now you can SSH to `ssh foobar-ingress` or `ssh foobar-private1`.
