### ISSUE TITLE
Setup your own scalable Kubernetes cluster with the Terraform provider for Hetzner Cloud

### ISSUE THREAD

**Issue by Jubeki** [hetzneronline/community-content#1122]
https://community.hetzner.com/tutorials/setup-your-own-scalable-kubernetes-cluster

Thanks for the great starting point of creating a kubernetes cluster.
While following the steps I encountered some questions / problems.

## Problem

1. Public IP for Worker nodes needed.

When removing the Public IP from Worker nodes, the tutorial no longer works, because it cannot correctly register with the master node. The issue seems to be that, normally the connection happens via the public IP instead of the private IP. But it seems to use the wrong private IP from the worker node. It uses `10.42.0.2`. instead of `10.0.1.2` which seems to relate to some kubernetes pods IP.

(I am not an kubernetes expert, But I would assume, that the setup should also work if only the master node has a Public IP and works as a Jump-Server for the other nodes.)

I do not have any idea, how to fix this.

2. Https Support

I also was a little baffled that no explanation about HTTPS support are mentioned.
I will provide a suggested fix below.

## Suggested Fix

For the 2. Problem: Https Support

Requirements:
- Domain managed by Hetzer DNS

You can do the following:
- Create a managed certificate on Cloud Console with the name `cluster-certificate`
- Use the following `example-service.yaml`

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: ingress-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ingress-nginx
  template:
    metadata:
      labels:
        app: ingress-nginx
    spec:
      containers:
      - name: app
        image: httpd:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  annotations:
    load-balancer.hetzner.cloud/name: "cluster-load-balancer"
    load-balancer.hetzner.cloud/location: "fsn1"
    load-balancer.hetzner.cloud/use-private-ip: "true"
    load-balancer.hetzner.cloud/protocol: "https"
    load-balancer.hetzner.cloud/http-certificates: "cluster-certificate"
    load-balancer.hetzner.cloud/http-redirect-http: "true"
    load-balancer.hetzner.cloud/private-ipv4: 10.0.1.254
spec:
  type: LoadBalancer
  selector:
    app: ingress-nginx
  ports:
    - protocol: TCP
      port: 443
      targetPort: 80
```

This added the annotations `protocol`, `http_certificates` with the name of the certificate, `http-redirect-http` for always redirecting http to https`.

And the private IP for the load balancer in the private network (this is optional).

There also is a change for the service port from 80 to 443.

Lastly you only need to add an A-Record to the load balancer to your Domain.
