### ISSUE TITLE
How-to: Hetzner Cloud Ansible modules - setting up hetzner server using ansible

### ISSUE THREAD

**Issue by melvmagr** [hetzneronline/community-content#467]
## Problem
While trying to create a hetzner server using ansible and following the below documentation; https://community.hetzner.com/tutorials/howto-hcloud-ansible

The playbook gets stuck for some reason and no server is created. Any ideas?

```
Using /home/melvmagr/repos/ansible/ansible.cfg as config file
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
redirecting (type: modules) ansible.builtin.hcloud_server to hetzner.hcloud.hcloud_server
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: server.yml ************************************************************************************
1 plays in playground/server.yml

PLAY [Create Basic Server] ******************************************************************************

TASK [Gathering Facts] **********************************************************************************
task path: /home/melvmagr/repos/ansible/playground/server.yml:3
ok: [localhost]
META: ran handlers

TASK [Create a basic server] ****************************************************************************
task path: /home/melvmagr/repos/ansible/playground/server.yml:11
redirecting (type: modules) ansible.builtin.hcloud_server to hetzner.hcloud.hcloud_server
```
Playbook is as follows;

```
# server.yml
---
- name: Create Basic Server
  hosts: localhost
  connection: local
  #gather_facts: False
  user: root
  vars:
    hcloud_token: "hetzner_API_token"
  tasks:
    - name: Create a basic server
      hcloud_server:
          api_token: "hetzner_API_token"
          name: test-server
          server_type: cx11
          #image: master-template-update-09-06-2022
          image: ubuntu-18.04
          state: present
      register: server
```
## Suggested Fix
