### ISSUE TITLE
How to install Ubuntu 20.04 with full disk encryption - DNS' are messed up

### ISSUE THREAD

**Issue by jaroslawjanas** [hetzneronline/community-content#622]
## Problem
For some reason, the **Hetzner** DNS' `185.12.64.1` and `185.12.64.1` are irreversibly "stuck".
Normally you can edit them using the netplan yaml config and disabling DNS in `dhclient.conf`.
But following these instructions will get them permanently stuck (at least for me).

I tried multiple reinstalls and variations.
I pretty much spent 3 days figuring this out.

I confirmed that with a normal install, this doesn't happen.

```
sudo resolvectl status
Global
       Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 2 (enp7s0)
Current Scopes: DNS
     Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
   DNS Servers: 1.1.1.1 1.0.0.1 185.12.64.1 185.12.64.2 2606:4700:4700::1111 2606:4700:4700::1001
    DNS Domain: your-server.de
```

## Suggested Fix

I have no idea.

**Comment by svenja11** [comment]
Hello @jaroslawjanas,

I followed the tutorial "[How to install Ubuntu 20.04 with full disk encryption](https://community.hetzner.com/tutorials/install-ubuntu-2004-with-full-disk-encryption)" to see if I have the same issue but I'm not entirely sure what you mean with "stuck".

You already mentioned that you edited the file in the `/etc/netplan` directory. Would it solve your issue if you also added `dhcp4-overrides` and set `use-dns` to false?

```yaml
### Hetzner Online GmbH installimage
network:
  [...]
  ethernets:
    ens3:
      [...]
      nameservers:
          addresses: [1.1.1.1, 1.0.0.1]
      dhcp4-overrides:
          use-dns: false
```

This should give you:

```bash
root@xyz:~# resolvectl status | grep "DNS Server" -A2

  Current DNS Server: 1.1.1.1
         DNS Servers: 1.1.1.1
                      1.0.0.1
```
