### ISSUE TITLE
JSON schema for the YAML front matter

### ISSUE THREAD

**Issue by wpdevelopment11** [hetzneronline/community-content#685]
I have written [JSON schema](https://json-schema.org/) which can catch some errors in the front matter automatically.

If you want to try it, you need to install:
* [Visual Studio Code](https://code.visualstudio.com/)
* [YAML extension by Red Hat](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml)

For now, you can't use it directly in `.md` file. See https://github.com/redhat-developer/vscode-yaml/issues/207.

You need to copy the front matter, paste it into a new file and set the language in the bottom right corner to YAML.
For example, let's take the front matter from `tutorial-template.md`, it contains some invalid values:

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/wpdevelopment11/community-content/json-schema/tutorials-schema.json
SPDX-License-Identifier: MIT
path: "/tutorials/tutorial-template"
slug: "tutorial-template"
date: "2023-01-01"
title: "A great Tutorial Template!"
short_description: "This is a tutorial template, including metadata (the first few lines before the actual tutorial). Please fill in as much as possible. If you don't know what to put somewhere, just leave it empty, the Community Manager will fill it for you. Your description should be less than 160 characters."
tags: ["Development", "Lang:Go", "Lang:JS"]
author: "Your Name"
author_link: "https://github.com/....."
author_img: "https://avatars3.githubusercontent.com/u/....."
author_description: "Manipulating arrays of characters in modern text editors that need more RAM than we used to fly to the moon. But it's super awesome..."
language: "en"
available_languages: ["en", "Enter all other available languages of the tutorial using ISO 639-1 codes"]
header_img: "header-x"
cta: "product"
```
Notice the first line which points to the JSON schema.

Here is a screenshot from the editor:

![tutorials-schema](https://github.com/hetzneronline/community-content/assets/85058595/78ed4197-e6d8-4e8b-a8bb-36e179949d88)

You can use a local file as a schema by specifying it like this:

```yaml
# yaml-language-server: $schema=file:///path/to/schema
```
