### ISSUE TITLE
How to set up Vaultwarden

### ISSUE THREAD

**Issue by SnakeEater96** [hetzneronline/community-content#730]
## Problem
I have followed the tutorial but can't get a certificate in no matter what I try

Error from the waf.log
```
[Sat Nov 25 17:44:23.431850 2023] [security2:notice] [pid 1:tid 140706225604480] ModSecurity: Status engine is currently disabled, enable it by setting SecStatusEngine to On.
[Sat Nov 25 17:44:23.508325 2023] [ssl:error] [pid 1:tid 140706225604480] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: OU=MyUnit,O=MyOrg,L=NY,ST=NY,C=US,emailAddress=none@none.com,CN=localhost / issuer: OU=MyUnit,O=MyOrg,L=NY,ST=NY,C=US,emailAddress=none@none.com,CN=localhost / serial: 1CEAE8BA01BDE18949BF49202299915702EFE0B1 / notbefore: Nov 25 17:44:23 2023 GMT / notbefore: Nov 24 17:44:23 2024 GMT]
[Sat Nov 25 17:44:23.508346 2023] [ssl:error] [pid 1:tid 140706225604480] AH02604: Unable to configure certificate localhost:443:0 for stapling
[Sat Nov 25 17:44:23.553645 2023] [mpm_event:notice] [pid 1:tid 140706225604480] AH00489: Apache/2.4.57 (Unix) OpenSSL/3.0.11 Apache configured -- resuming normal operation
[Sat Nov 25 17:44:23.553669 2023] [core:notice] [pid 1:tid 140706225604480] AH00094: Command line: 'httpd -D FOREGROUN
```

compose.yml:

```
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=acme@snakeeater96.com
      - --certificatesresolvers.myresolver.acme.storage=acme.json
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/docker/le:/letsencrypt

  waf:
    image: owasp/modsecurity-crs:apache
    container_name: waf
    environment:
      PARANOIA: 1
      ANOMALY_INBOUND: 10
      ANOMALY_OUTBOUND: 5
      PROXY: 1
      REMOTEIP_INT_PROXY: "172.20.0.1/16"
      BACKEND: "http://vaultwarden:80"
      BACKEND_WS: "ws://vaultwarden:80/notifications/hub"
      ERRORLOG: "/var/log/waf/waf.log"
    volumes:
     - /opt/docker/waf:/var/log/waf
     - /opt/docker/waf-rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
     - /opt/docker/waf-rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.redirect-https.redirectScheme.scheme=https
      - traefik.http.middlewares.redirect-https.redirectScheme.permanent=true
      - traefik.http.routers.vw-ui-https.rule=Host(`vaultwarden.snakeeater96.com`)
      - traefik.http.routers.vw-ui-https.entrypoints=websecure
      - traefik.http.routers.vw-ui-https.tls=true
      - traefik.http.routers.vw-ui-https.service=vw-ui
      - traefik.http.routers.vw-ui-http.rule=Host(`vaultwarden.snakeeater96.com`)
      - traefik.http.routers.vw-ui-http.entrypoints=web
      - traefik.http.routers.vw-ui-http.middlewares=redirect-https
      - traefik.http.routers.vw-ui-http.service=vw-ui
      - traefik.http.services.vw-ui.loadbalancer.server.port=80
      - traefik.http.routers.vw-websocket-https.rule=Host(`vaultwarden.snakeeater96.com`) && Path(`/notifications/hub`)
      - traefik.http.routers.vw-websocket-https.entrypoints=websecure
      - traefik.http.routers.vw-websocket-https.tls=true
      - traefik.http.routers.vw-websocket-https.service=vw-websocket
      - traefik.http.routers.vw-websocket-http.rule=Host(`vaultwarden.snakeeater96.com`) && Path(`/notifications/hub`)
      - traefik.http.routers.vw-websocket-http.entrypoints=web
      - traefik.http.routers.vw-websocket-http.middlewares=redirect-https
      - traefik.http.routers.vw-websocket-http.service=vw-websocket
      - traefik.http.services.vw-websocket.loadbalancer.server.port=3012
  ```

i have my domain by cloudflare
## Suggested Fix

**Comment by svenja11** [comment]
I have checked the tutorial and it seems to be fine.

* DNS records<br>
  Did you check if your domain is correctly resolved before you tried to get the certificate? Sometimes it can take a while to update after you added a new record.

<br>

* `docker-compose.yml`<br>
  You could try and remove `--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json` to avoid any conflicts.

----------

Or were you able to fix the issue yourself by now?

**Comment by SnakeEater96** [comment]
Habe Das direkt so gemacht wie das in deiner Anleitung steht

Aber es wird kein Zertifikat erstellt


Kollege hat das bei sich getestet und das selbe Problem

Sven-Ole Seehusen ***@***.***> schrieb am Mi., 6. Dez. 2023,
13:47:

**Comment by svenja11** [comment]
Tut mir Leid, dass es ein wenig gedauert hat. Ich musste es selbst nochmal testen, glaube aber das Problem evtl. gefunden zu haben.

Versuche es mal indem du folgende zwei "waf"-Label in der `docker-compose.yml`-Datei ergänzt:

```yml
      - traefik.http.routers.vw-ui-https.tls.certresolver=myresolver
      - traefik.http.routers.vw-websocket-https.tls.certresolver=myresolver
```

<blockquote>

<details>

<summary>Hier klicken, um den gesamten "waf"-Teil in der `docker-compose.yml`-Datei anzusehen</summary>

```yml
  waf:
    image: owasp/modsecurity-crs:apache
    container_name: waf
    environment:
      PARANOIA: 1
      ANOMALY_INBOUND: 10
      ANOMALY_OUTBOUND: 5
      PROXY: 1
      REMOTEIP_INT_PROXY: "172.20.0.1/16"
      BACKEND: "http://vaultwarden:80"
      BACKEND_WS: "ws://vaultwarden:80/notifications/hub"
      ERRORLOG: "/var/log/waf/waf.log"
    volumes:
     - /opt/docker/waf:/var/log/waf
     - /opt/docker/waf-rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
     - /opt/docker/waf-rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.redirect-https.redirectScheme.scheme=https
      - traefik.http.middlewares.redirect-https.redirectScheme.permanent=true
      - traefik.http.routers.vw-ui-https.rule=Host(`sub.domain.tld`)
      - traefik.http.routers.vw-ui-https.entrypoints=websecure
      - traefik.http.routers.vw-ui-https.tls=true
      - traefik.http.routers.vw-ui-https.service=vw-ui
      - traefik.http.routers.vw-ui-http.rule=Host(`sub.domain.tld`)
      - traefik.http.routers.vw-ui-http.entrypoints=web
      - traefik.http.routers.vw-ui-http.middlewares=redirect-https
      - traefik.http.routers.vw-ui-http.service=vw-ui
      - traefik.http.routers.vw-ui-https.tls.certresolver=myresolver
      - traefik.http.services.vw-ui.loadbalancer.server.port=80
      - traefik.http.routers.vw-websocket-https.rule=Host(`sub.domain.tld`) && Path(`/notifications/hub`)
      - traefik.http.routers.vw-websocket-https.entrypoints=websecure
      - traefik.http.routers.vw-websocket-https.tls=true
      - traefik.http.routers.vw-websocket-https.service=vw-websocket
      - traefik.http.routers.vw-websocket-http.rule=Host(`sub.domain.tld`) && Path(`/notifications/hub`)
      - traefik.http.routers.vw-websocket-http.entrypoints=web
      - traefik.http.routers.vw-websocket-http.middlewares=redirect-https
      - traefik.http.routers.vw-websocket-http.service=vw-websocket
      - traefik.http.routers.vw-websocket-https.tls.certresolver=myresolver
      - traefik.http.services.vw-websocket.loadbalancer.server.port=3012
```

</details>

</blockquote>

-------------------

Erhält deine Seite mit dieser Änderung nun ein SSL-Zertifikat?
