### ISSUE TITLE
Setup your own scalable Kubernetes cluster with the Terraform provider for Hetzner Cloud

### ISSUE THREAD

**Issue by Mawiguk0** [hetzneronline/community-content#827]
## Problem
The k3s.yml file to download via scp is not beeing owned by the cluster user, therefore cant be downloaded.
```bash
➜  production scp -i ~/.ssh/id_ed25519.pub cluster@<master-node-ip>:/etc/rancher/k3s/k3s.yaml ./config
scp: /etc/rancher/k3s/k3s.yaml: Permission denied
```
The file ownership:
```bash
cluster@master-node:/etc/rancher/k3s$ ls -lah
total 12K
drwxr-xr-x 2 root root 4.0K Apr 21 10:51 .
drwxr-xr-x 4 root root 4.0K Apr 21 10:51 ..
-rw------- 1 root root 2.9K Apr 21 10:51 k3s.yaml
```
## Suggested Fix
There are alot of ways to fix this issue, the easiest two would be:
### Option 1:
Add a pubkey to the root user of the master node, then copy the k3s.yaml with the root user.
### Option 2:
Before Using SCP add:
Login to the master node with ssh and the cluster user:
`ssh cluster@<master-node-ip>`
Switch to the root user:
`sudo -i`
Copy the k3s.yaml to the cluster users home directory:
`cp /etc/rancher/k3s/k3s.yaml /home/cluster/config `
Change the file ownership to the cluster user:
`chown cluster:cluster /home/cluster/config`

## Comment
It is lowkey/subtle insane to add this kind of beginner steps to a guide on how to setup a k3s cluster. Everybody doing this, should know already, how to solve this problem. But the guide in this form is simply not working, if applied with little to no attention to details.

**Comment by svenja11** [comment]
@Blue25GD You wrote the tutorial. Can you take a look at this and update your tutorial as needed?

**Comment by Blue25GD** [comment]
Hey there,

I have added the following lines to the master node cloud-config:
```yaml
#cloud-config
packages:
  - curl
users:
  - name: cluster
    ssh-authorized-keys:
      - <your-ssh-public-key>
      - <worker_public_ssh_key>
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
runcmd:
  - apt-get update -y
  - curl https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik" sh -
**+  - chown cluster:cluster /etc/rancher/k3s/k3s.yaml
+  - chown cluster:cluster /var/lib/rancher/k3s/server/node-token**
```

They should fix this problem, although it seems that you have not followed the tutorial correctly...
