### ISSUE TITLE
How to set up NAT gateway for private Cloud Networks

### ISSUE THREAD

**Issue by paulrogov** [hetzneronline/community-content#947]
## Problem
1. Persistent configuration for Ubuntu 24.04 client servers _(CX22 instance)_ does not work.
2. There is not DNS config for Ubuntu client servers specified at all.

## Reason
A Hetzner Ubuntu 24.04 CX22 has network interface named `enp7s0`, not `ens10` mentioned in the current version of the document.

## Suggested Fix
Tested with Ubuntu 24.04 CX22
1. Change to `enp7s0` (can be double-checked with `ifconfig` output)
```bash
$ nano /etc/systemd/network/10-enp7s0.network
```
```bash
[Match]
Name=enp7s0

[Network]
DHCP=yes
Gateway=10.0.0.1
```
```bash
$ reboot
```

2. Add DNS config
```bash
$ nano /etc/systemd/resolved.conf
```
```
DNS=1.1.1.1 FallbackDNS=8.8.8.8 # Cloudflare and Google Fallback
```
```bash
$ sudo systemctl restart systemd-resolved
```

**Comment by paulrogov** [comment]
Optionally, you can use this `cloud-init` config for persistent config on Ubuntu 24.04 client servers.
This is in `yaml` format and should be specified when creating a new server instance _(tested with Hetzner Ubuntu 24.04 CX22)_:

```yaml
#cloud-config
package_update: true
package_upgrade: true # optional
package_reboot_if_required: true # optional

packages:
  - ifupdown

write_files:
  - path: /etc/systemd/network/10-ens10.network
    content: |
      # Custom network configuration added by cloud-init
      [Match]
      Name=ens10

      [Network]
      DHCP=yes
      Gateway=10.0.0.1
    append: true

  - path: /etc/systemd/network/10-enp7s0.network
    content: |
      # Custom network configuration added by cloud-init
      [Match]
      Name=enp7s0

      [Network]
      DHCP=yes
      Gateway=10.0.0.1
    append: true

  - path: /etc/systemd/resolved.conf
    content: |
      # Custom network configuration added by cloud-init
      DNS=1.1.1.1 FallbackDNS=8.8.8.8 # Cloudflare and Google Fallback
    append: true

runcmd:
  - reboot
```

**Comment by GeorgeJose7** [comment]
I was unable to use this configuration to connect. 

I used the following cloud init config 
# Nat server
```YAML
#cloud-config
package_update: true
package_upgrade: true
runcmd:
  - |
    cat <<'EOF' >> /etc/networkd-dispatcher/routable.d/10-enp7s0-post-up
    #!/bin/bash
    
    echo 1 > /proc/sys/net/ipv4/ip_forward
    iptables -t nat -A POSTROUTING -s '10.0.0.0/16' -o enp7s0 -j MASQUERADE
    EOF
    chmod +x /etc/networkd-dispatcher/routable.d/10-enp7s0-post-up
  - reboot
```

# Client
```YAML
#cloud-config
write_files:
  - path: /etc/systemd/network/10-enp7s0.network
    content: |
      # Custom network configuration added by cloud-init
      [Match]
      Name=enp7s0

      [Network]
      DHCP=yes
      Gateway=10.0.0.1
    append: true

  - path: /etc/systemd/resolved.conf
    content: |
      # Custom network configuration added by cloud-init
      DNS=1.1.1.1 FallbackDNS=8.8.8.8 # Cloudflare and Google Fallback
    append: true

runcmd:
  - reboot
```

and then added the rule. 

The client was still unable to reach the internet. I tried pinging 8.8.8.8 and google.com 

Am I missing something?
